DROP TABLE IF EXISTS SNEAKER, SNEAKER_STOCK;

CREATE TABLE SNEAKER(
    SNEAKER_ID       BIGINT       NOT NULL,
    CREATED_AT       TIMESTAMP    NOT NULL,
    UPDATED_AT       TIMESTAMP    NOT NULL,
    CODE             VARCHAR(10) NOT NULL,
    DESCRIPTION      CLOB         NOT NULL,
    MEMBER_CATEGORY  VARCHAR(10)  NOT NULL,
    NAME             VARCHAR(50)  NOT NULL,
    PRICE            INTEGER      NOT NULL,
    RELEASE_DATE     TIMESTAMP    NOT NULL,
    SNEAKER_CATEGORY VARCHAR(20)  NOT NULL,
    PRIMARY KEY (SNEAKER_ID)
);

CREATE TABLE SNEAKER_STOCK(
    SNEAKER_STOCK_ID BIGINT    NOT NULL,
    CREATED_AT       TIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP NOT NULL,
    SIZE             INTEGER   NOT NULL,
    QUANTITY         INTEGER   NOT NULL,
    SNEAKER_ID       BIGINT    NOT NULL,
    PRIMARY KEY (SNEAKER_STOCK_ID)
);
